### ISSUE TITLE
How to solve issue with ceres-solver

### ISSUE THREAD

**Issue by sounkalo** [avkudr/pollen3d#1]
The control "cmake .. -DCMAKE_BUILD_TYPE=Release" gives the following message:
-- compiling in release
-- OpenMP - FOUND
Eigen3: found
OpenCV: found
nlopt: found
CMake Error at lib/CMakeLists.txt:146 (find_package):
  By not providing "Findceres-solver.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ceres-solver", but CMake did not find one.

  Could not find a package configuration file provided by "ceres-solver" with
  any of the following names:

    ceres-solverConfig.cmake
    ceres-solver-config.cmake

  Add the installation prefix of "ceres-solver" to CMAKE_PREFIX_PATH or set
  "ceres-solver_DIR" to a directory containing one of the above files.  If
  "ceres-solver" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/sounkalo.dembele/pollen3d/build/CMakeFiles/CMakeOutput.log".

The solution is to replace in the file "CMakeList.txt" from the folder pollen3d/lib "ceres-solver" by "Ceres".

**Comment by Yucely** [comment]
Once the library is installed with make install, it is possible to use CMake with find_package(Ceres REQUIRED QUIET) in order to compile user code against Ceres; I think your problem is that you have find_package(ceres-solver REQUIRED QUIET). It would help if you changed "ceres-solver" to "Ceres" everywhere you call the package.
` find_package(Ceres REQUIRED QUIET) `

**Comment by avkudr** [comment]
Hello @sounkalo @Yucely. Thanks for spotting an issue. Did you test on all the platforms: Windows, Linux, Mac? In the future, a good mechanism for suggesting changes in the code would be to use [pull requests](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests)
